channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - folium=0.20.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - gdal=3.12.1
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.14.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarchive=3.8.5
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libdeflate=1.25
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-arrow-parquet=3.12.1
  - libgdal-core=3.12.1
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libparquet=23.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.3
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - minizip=4.0.10
  - mkl=2025.3.0
  - munkres=1.1.4
  - muparser=2.3.5
  - networkx=3.6.1
  - numpy=2.4.1
  - openjpeg=2.5.4
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=26.0
  - pandas=3.0.0
  - pcre2=10.47
  - pillow=12.1.0
  - pip=25.3
  - proj=9.7.1
  - pthread-stubs=0.4
  - pyarrow-core=23.0.0
  - pyogrio=0.12.1
  - pyparsing=3.3.2
  - pyproj=3.7.2
  - pysocks=1.7.1
  - python=3.14.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.14
  - qhull=2020.2
  - re2=2025.11.05
  - requests=2.32.5
  - scikit-learn=1.8.0
  - setuptools=80.10.2
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - win_inet_pton=1.1.0
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - pyarrow==23.0.0
      - scipy==1.17.0

